language: objective-c
osx_image: xcode10
sudo: false
env:
  global:
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
script: 
  - set -o pipefail
  - xcodebuild -project IGRPhotoTweaks.xcodeproj -target IGRPhotoTweaks -sdk iphonesimulator
